# Generated by Django 5.2.17 on 2026-10-05 17:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(help_text="What is communicated, e.g. 'Construction progress'.", max_length=200)),
                ('audience', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('MEETING', 'Meeting'), ('EMAIL', 'Email'), ('REPORT', 'Written report'), ('PRESENTATION', 'Presentation'), ('PUBLIC_NOTICE', 'Public notice / door hanger'), ('WEBSITE', 'Website / social media'), ('NEWSLETTER', 'Newsletter')], max_length=20)),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Every two weeks'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('MILESTONE', 'At milestones'), ('AS_NEEDED', 'As needed')], max_length=20)),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_items', to='pm.project')),
            ],
            options={
                'verbose_name': 'communication plan item',
                'ordering': ['project', 'purpose'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('planned_date', models.DateField(help_text='Baseline date from the approved plan.')),
                ('forecast_date', models.DateField(blank=True, help_text='Current expected date.', null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('AT_RISK', 'At Risk'), ('COMPLETE', 'Complete'), ('MISSED', 'Missed')], default='NOT_STARTED', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='pm.project')),
            ],
            options={
                'ordering': ['project', 'planned_date'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=300)),
                ('success_measure', models.CharField(blank=True, help_text='How will we know it was achieved?', max_length=300)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('ON_TRACK', 'On Track'), ('AT_RISK', 'At Risk'), ('ACHIEVED', 'Achieved'), ('NOT_ACHIEVED', 'Not Achieved')], default='NOT_STARTED', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lowest first).')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='pm.project')),
            ],
            options={
                'ordering': ['project', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('problem_statement', models.TextField(blank=True, help_text='What problem or need does this project address, and why now?')),
                ('scope_in', models.TextField(blank=True, help_text='Work, deliverables and areas included in the project.', verbose_name='in scope')),
                ('scope_out', models.TextField(blank=True, help_text='Explicit exclusions, to prevent scope creep.', verbose_name='out of scope')),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='pm.project')),
            ],
            options={
                'verbose_name': 'project plan',
                'ordering': ['-project__project_id'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technical / Design'), ('SCHEDULE', 'Schedule'), ('COST', 'Cost / Funding'), ('REGULATORY', 'Regulatory / Permitting'), ('ENVIRONMENTAL', 'Environmental'), ('SAFETY', 'Safety'), ('STAKEHOLDER', 'Stakeholder / Community'), ('OPERATIONS', 'Operations'), ('PROCUREMENT', 'Procurement / Supply Chain')], max_length=20)),
                ('likelihood', models.PositiveSmallIntegerField(choices=[(1, '1 — Rare'), (2, '2 — Unlikely'), (3, '3 — Possible'), (4, '4 — Likely'), (5, '5 — Almost certain')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impact', models.PositiveSmallIntegerField(choices=[(1, '1 — Negligible'), (2, '2 — Minor'), (3, '3 — Moderate'), (4, '4 — Major'), (5, '5 — Severe')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('score', models.PositiveSmallIntegerField(default=1, editable=False, help_text='Likelihood × impact.')),
                ('owner', models.CharField(blank=True, help_text='Person responsible for managing the risk.', max_length=200)),
                ('mitigation', models.TextField(blank=True, verbose_name='mitigation / response')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MITIGATING', 'Mitigating'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('identified_date', models.DateField(default=django.utils.timezone.localdate)),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='next review')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='pm.project')),
            ],
            options={
                'ordering': ['-score', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Person or group.', max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, help_text='Role on or interest in the project.', max_length=200)),
                ('influence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('interest', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('engagement_notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='pm.project')),
            ],
            options={
                'ordering': ['project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_type', models.CharField(choices=[('MONTHLY', 'Monthly update'), ('DECISION', 'Decision'), ('ISSUE', 'Issue'), ('GENERAL', 'General note')], default='MONTHLY', max_length=20)),
                ('period', models.DateField(blank=True, help_text='For monthly updates: the month being reported on (stored as the 1st of the month).', null=True, verbose_name='reporting month')),
                ('note_date', models.DateField(default=django.utils.timezone.localdate)),
                ('author_name', models.CharField(max_length=200, verbose_name='author')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_notes', to='pm.project')),
            ],
            options={
                'verbose_name': 'activity note',
                'ordering': ['-note_date', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('note_type', 'MONTHLY')), fields=('project', 'period'), name='one_monthly_update_per_project_month', violation_error_message='This project already has a monthly update for that month.')],
            },
        ),
    ]
