# Generated by Django 5.2.17 on 2026-10-04 18:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('project_id', models.CharField(help_text='Manually assigned identifier, e.g. 2021-2-20-0. Must be unique.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Project ID must look like 2021-2-20-0 (year-#-#-#).', regex='^\\d{4}-\\d+-\\d+-\\d+$')], verbose_name='project ID')),
                ('budget_id', models.CharField(db_index=True, help_text='Budget/fund number, e.g. 6822015. May be shared by several projects.', max_length=20, validators=[django.core.validators.RegexValidator(message='Budget ID must contain digits only (e.g. 6822015).', regex='^\\d+$')], verbose_name='budget ID')),
                ('project_type', models.CharField(choices=[('CIP', 'CIP'), ('DEVELOPMENT', 'Development'), ('ENVIRONMENTAL', 'Environmental')], max_length=20)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('DESIGN', 'Design'), ('CONSTRUCTION', 'Construction'), ('ON_HOLD', 'On Hold'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='PLANNING', max_length=20)),
                ('project_manager', models.CharField(help_text="Project manager's name.", max_length=200)),
            ],
            options={
                'ordering': ['-project_id'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('mailing_address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('primary_contact_name', models.CharField(blank=True, max_length=200)),
                ('primary_contact_phone', models.CharField(blank=True, max_length=40, verbose_name='primary contact phone number')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FieldReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.CharField(help_text='Name of the person who wrote the report.', max_length=200)),
                ('report_date', models.DateField(verbose_name='field report date')),
                ('data_entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('time_on_site', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='time on site (hours)')),
                ('observation_notes', models.TextField(blank=True)),
                ('safety_notes', models.TextField(blank=True)),
                ('weather_notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_reports', to='pm.project')),
            ],
            options={
                'verbose_name': 'field report',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=300)),
                ('originating_organization', models.CharField(max_length=200)),
                ('recipient_organization', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('LETTER', 'Letter'), ('MEMO', 'Memo'), ('EMAIL', 'Email'), ('RFI', 'RFI'), ('SUBMITTAL', 'Submittal'), ('CHANGE_ORDER', 'Change Order'), ('MEETING_MINUTES', 'Meeting Minutes'), ('REPORT', 'Report'), ('DRAWING', 'Drawing'), ('OTHER', 'Other')], max_length=20)),
                ('document_date', models.DateField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('last_edited_date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pm.project')),
            ],
            options={
                'ordering': ['-document_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po_number', models.CharField(max_length=50, unique=True, verbose_name='purchase order number')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('contract_number', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, help_text='Project this PO is charged to (optional).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='pm.project')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='pm.vendor')),
            ],
            options={
                'verbose_name': 'purchase order',
                'ordering': ['-po_number'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(help_text="Vendor's invoice number.", max_length=50)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='RECEIVED', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('invoice_date', models.DateField()),
                ('received_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='pm.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='pm.vendor')),
            ],
            options={
                'ordering': ['-invoice_date'],
                'constraints': [models.UniqueConstraint(fields=('vendor', 'invoice_number'), name='unique_invoice_per_vendor')],
            },
        ),
    ]
