# Generated by Django 5.2.17 on 2026-10-05 23:12

import django.db.models.deletion
import uuid
from django.db import migrations, models

# Old project types -> new. "CIP" didn't distinguish expansion from renewal &
# replacement, so existing CIP and Environmental projects become CIP R&R; reclassify
# expansion projects afterwards as needed.
FORWARD = {"CIP": "CIP_RR", "ENVIRONMENTAL": "CIP_RR"}
BACKWARD = {"CIP_RR": "CIP", "CIP_EXPANSION": "CIP"}


def remap_project_types(mapping):
    def run(apps, schema_editor):
        Project = apps.get_model("pm", "Project")
        for old, new in mapping.items():
            Project.objects.filter(project_type=old).update(project_type=new)

    return run


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='unit name')),
                ('unit_type', models.CharField(choices=[('WATER_USE_PERMIT', 'Water Use Permit'), ('PUBLIC_WATER_SUPPLY', 'Public Water Supply'), ('WASTEWATER', 'Wastewater'), ('TANK', 'Tank'), ('STORMWATER', 'Stormwater'), ('OTHER', 'Other')], max_length=30)),
            ],
            options={
                'verbose_name': 'compliance unit',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='pm.invoice'),
        ),
        migrations.AddField(
            model_name='document',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='pm.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='pm.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('CIP_EXPANSION', 'CIP Expansion'), ('CIP_RR', 'CIP R&R'), ('DEVELOPMENT', 'Development')], max_length=20),
        ),
        migrations.RunPython(remap_project_types(FORWARD), remap_project_types(BACKWARD)),
        migrations.AddField(
            model_name='document',
            name='compliance_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='pm.complianceunit'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('project__isnull', False), ('compliance_unit__isnull', False), ('purchase_order__isnull', False), ('invoice__isnull', False), _connector='OR'), name='document_has_link', violation_error_message='Link the document to at least one project, compliance unit, purchase order or invoice.'),
        ),
    ]
